<?php if($this->isAllowed('form')): ?>	
	<div class="aright"><?php echo $this->ajax("new", 'activity/index/form/', 2); ?></div>
<?php endif; ?>	
<?php if (count($this->data)):?>
    <table class="zebra-striped">
            <tr>
                <th><?php echo $this->translate('Title')?></th>
                <th><?php echo $this->translate('End')?></th>
                <th></th>
            </tr>
        <?php foreach ($this->data as $data): ?>
            <tr>
                <td><?php echo $this->ajax($data->title, 'activity/text/index/id/' . $data->id);?></td>
                <td><?php echo $data->end ? $this->date($data->end) : $this->translate('Free');?></td>
                <td nowrap="nowrap" width="60">
                    <?php if ($this->isAllowed('form')): ?>
                        <?php echo $this->ajax("edit", 'activity/index/form/id/'. $data->id, 2); ?>
                    <?php endif;?>
                </td>
            </tr>
        <?php endforeach;?>
    </table>
    <div id="activity-page">
        <?php echo $this->paginationControl($this->data) ?>
    </div>
<?php else:?>
    <p><?php echo $this->translate( "there are no records" );?></p>
<?php endif;?>
<script type="text/javascript">
    $('#activity-page a').click(function(){
        $(this).parents('.content').load(this.href);
        return false;
    });

    $("#formFindActivity").submit(function(ev) {
		$(this).parents('.content').load('activity/index/index/q/' + $('#qActivity').val());
        return false;
	});
</script>